use blake2::{Blake2b512, Digest};
use chrono::Utc;
use std::sync::atomic::{AtomicBool, Ordering};
use anyhow::{Result, bail};
use zeroize::Zeroize;
use std::fs::{self, OpenOptions};
use std::io::{Read, Write, Seek, SeekFrom};

// Include the constants generated by build.rs
include!(concat!(env!("OUT_DIR"), "/identity_consts.rs"));

pub static TAMPERED: AtomicBool = AtomicBool::new(false);

/// Initializes the self-defense checks.
/// This is the FIRST line of defense.
pub fn init(email: &str, store_id: &str) -> Result<()> {
    check_identity(email, store_id, EMBEDDED_REFERRAL_ID)?;
    check_integrity()?;
    check_time_bomb()?;
    
    Ok(())
}

fn check_identity(email: &str, store_id: &str, referral_id: &str) -> Result<()> {
    let mut hasher = Blake2b512::new();
    hasher.update(format!("{}|{}", email, store_id).as_bytes());
    let intermediate_hash = hasher.finalize();

    let mut final_hasher = Blake2b512::new();
    final_hasher.update(&intermediate_hash);
    final_hasher.update(referral_id.as_bytes());
    let current_hash = final_hasher.finalize();

    if current_hash.as_slice() != EMBEDDED_USER_HASH || referral_id != EMBEDDED_REFERRAL_ID {
        TAMPERED.store(true, Ordering::SeqCst);
        let err_msg = format!(
            "\n❌ LICENSE ERROR\nThis copy is registered to a different organization.\nYou entered: {}\n\nFix: Run build.bat again with your correct email.",
            email
        );
        eprintln!("{}", err_msg);
        std::process::exit(1);
    }
    Ok(())
}

fn check_integrity() -> Result<()> {
    // In WASI, we assume the executable is accessible at a standard path 
    // or provided via the runtime configuration.
    let exe_path = std::env::current_exe().unwrap_or_else(|_| std::path::PathBuf::from("trueroas.wasm"));
    
    let mut file = match fs::File::open(&exe_path) {
        Ok(f) => f,
        Err(_) => return Ok(()), // If we can't read ourselves, we are likely in a restricted sandbox
    };

    let metadata = file.metadata()?;
    let size = metadata.len();
    if size < 64 { bail!("Binary too small"); }

    let mut buffer = Vec::new();
    file.read_to_end(&mut buffer)?;

    // Hash everything except the last 64 bytes (reserved for future signature)
    let mut hasher = Blake2b512::new();
    hasher.update(&buffer[..buffer.len() - 64]);
    let calculated_hash = hasher.finalize();

    // Verify against embedded hash (Requirement: EMBEDDED_BINARY_HASH must be added to build.rs)
    if calculated_hash.as_slice() != &buffer[buffer.len() - 64..] {
        TAMPERED.store(true, Ordering::SeqCst);
        eprintln!("\n❌ INTEGRITY ERROR");
        eprintln!("File corrupted – please re-download from trueroas.com");
        std::process::exit(1);
    }

    Ok(())
}

fn poison_binary(path: &std::path::Path) {
    if let Ok(mut file) = OpenOptions::new().write(true).open(path) {
        let zero_fill = vec![0u8; 1024 * 1024]; // 1MB poison
        let _ = file.seek(SeekFrom::Start(0));
        let _ = file.write_all(&zero_fill);
    }
}

fn check_time_bomb() -> Result<()> {
    let now = Utc::now().timestamp();
    if now > BUILD_EXPIRY_TS {
        // We check a mock referral count. In Phase 3 this will be in the Vault.
        let referrals = 0; 
        if referrals < 3 {
            eprintln!("\n⏰ LICENSE EXPIRED");
            eprintln!("Please invite 3 users to renew your access or contact the founders.");
            std::process::exit(1);
        }
    }
    Ok(())
}

/// Called by export_csv to check if data should be poisoned.
pub fn apply_tamper_poison(original_roas: f64) -> f64 {
    if TAMPERED.load(Ordering::SeqCst) {
        use rand::Rng;
        let mut rng = rand::thread_rng();
        let noise: f64 = rng.gen_range(0.0..0.1);
        return original_roas * (0.5 + noise);
    }
    original_roas
}

pub fn check_hardware_binding(vault: &crate::vault::Vault, current_fp: [u8; 32]) -> Result<()> {
    let conn = vault.get_connection();
    conn.execute("CREATE TABLE IF NOT EXISTS sys_binding (fp BLOB, count INTEGER)", [])?;
    
    let mut stmt = conn.prepare("SELECT fp, count FROM sys_binding LIMIT 1")?;
    let existing: Option<(Vec<u8>, i32)> = stmt.query_row([], |r| Ok((r.get(0)?, r.get(1)?))).ok();

    match existing {
        None => {
            conn.execute("INSERT INTO sys_binding (fp, count) VALUES (?, 0)", [current_fp.to_vec()])?;
        }
        Some((fp, count)) => {
            if fp != current_fp {
                conn.execute("UPDATE sys_binding SET count = count + 1", [])?;
                if count >= 2 { TAMPERED.store(true, Ordering::SeqCst); }
            }
        }
    }
    Ok(())
}